# URL de conexão (ajuste localhost e a porta se necessário)
spring.datasource.url=jdbc:postgresql://localhost:5432/petiscaria
spring.datasource.username=admin_petiscaria
spring.datasource.password=Wkldjr58*

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' cria as tabelas automaticamente se elas não existirem
spring.jpa.hibernate.ddl-auto=update
# Mostra o SQL no console (bom para debug)
spring.jpa.show-sql=true

# Para ver o erro completo no console do Java
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always
logging.level.dev.petiscaria=DEBUG
logging.level.org.springframework.web=DEBUG

api.security.token.secret=${JWT_SECRET:alguma_coisa_sobre_a_petiscaria_que_eh_de_2026_e_sla_mais_o_que"}