# Usa o nome do serviço 'db' definido no docker-compose
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/petiscaria
spring.datasource.username=${DB_USER:admin_petiscaria}
spring.datasource.password=${DB_PASSWORD:Wkldjr58@Thiago}

# Segredo JWT vindo do ambiente
api.security.token.secret=${JWT_SECRET:petiscaria_2026_api_comanda_petiscaria_thiago_aroldo_daiane}

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' cria as tabelas automaticamente se elas não existirem
spring.jpa.hibernate.ddl-auto=update
# Mostra o SQL no console (bom para debug)
spring.jpa.show-sql=true

# Para ver o erro completo no console do Java
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always
logging.level.dev.petiscaria=DEBUG
logging.level.org.springframework.web=DEBUG